kind: PersistentVolume
apiVersion: v1
metadata:
  name: glasswalltarget-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/c/test-data-output"