# The final solution will likely not have a PV at all but instead use
# dynamic provisioning off of the pvc. For testing this is fine, of course,
# although I would make the path configurable through values
kind: PersistentVolume
apiVersion: v1
metadata:
  name: glasswallsource-pv
  labels:
    type: local
spec:
  storageClassName: glasswallsource
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/test-data"